export const QUERY_KEYS = {
  HERO_BANNER: 'hero-banner',
  ADMIN_BANNERS: 'admin-banners',
  CATEGORIES: 'categories',
  SHOPS: 'shops',
  PRODUCTS: 'products',
  PUBLIC_PRODUCTS: 'public-products',
  PRODUCT_QUESTIONS: 'product-questions',
  CART: 'cart',
  ORDERS: 'orders',
  VENDOR_ORDERS: 'vendor-orders',
  ADMIN_ORDERS: 'admin-orders',
  VOUCHERS: 'vouchers',
  WALLET: 'wallet',
  WISHLIST: 'wishlist',
};
